### ISSUE TITLE
问题请教：请问显示地自定义边界存储是不是就是每次时间步都在反传梯度？

### ISSUE THREAD

**Issue by liufeng2317** [GeophyAI/seistorch#4]
你好，非常棒的工作，我也是在做ADFWI的工作，看到你这个边界存储的想法很好，但是我有一个疑问：
就是我看你的checkpoint代码中是每个时间步其实都是要计算梯度的，那么这样和直接使用 torch.utils.checkpoint的区别似乎不是很大，因为将torch.utils.checkpoint的segment设置大一些也有相同的效果？

**Comment by GeophyAI** [comment]
Hi你好，很高兴你对我们的工作感兴趣。这里的边界存储在forward过程中只存储了波场的边界信息并在bachward用边界重构中心波场，与torch.utils.checkpoint是完全不同的东西，代码中只是借用了这一函数的封装。

---- Replied Message ----
| From | Liu ***@***.***> |
| Date | 10/21/2024 06:22 |
| To | GeophyAI/seistorch ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [GeophyAI/seistorch] 问题请教：请问显示地自定义边界存储是不是就是每次时间步都在反传梯度？ (Issue #4) |

你好，非常棒的工作，我也是在做ADFWI的工作，看到你这个边界存储的想法很好，但是我有一个疑问：
就是我看你的checkpoint代码中是每个时间步其实都是要计算梯度的，那么这样和直接使用 torch.utils.checkpoint的区别似乎不是很大，因为将torch.utils.checkpoint的segment设置大一些也有相同的效果？
